// Hermes v0.13.0 sync — May 2026 (Ronbot)
import { formatAppRoutesForAgentGuide } from '@/lib/appRoutes';

/**
 * Static markdown Ronbot writes for the agent to read (UI protocol only).
 * Does not override Hermes tools, skills, or conversation style.
 *
 *   - RONBOT_RULES_BLOCK   → ~/.hermes/AGENTS.md managed block
 *   - RONBOT_APP_GUIDE     → ~/.ronbot/APP_GUIDE.md
 *   - RONBOT_ELECTRON_APP_GUIDE → ~/.hermes/ELECTRON_APP_GUIDE.md
 *
 * Bump version headers when content changes so guides refresh on connect.
 */

/** One-liner appended to seeded MEMORY.md when Ronbot manages persona files. */
export const RONBOT_MEMORY_UI_POINTER =
  '- **Ronbot UI:** Optional fenced ```ronbot-intent``` cards and stream markers — see `~/.ronbot/APP_GUIDE.md` and `~/.hermes/ELECTRON_APP_GUIDE.md`.';

export const RONBOT_RULES_BLOCK = [
  '## Ronbot desktop UI (reference)',
  '',
  'Ronbot is the chat shell around Hermes on this machine. Hermes behavior is unchanged.',
  '',
  '- **Chat** renders Markdown, Mermaid, and optional ```ronbot-intent``` JSON cards.',
  '- **Stream markers** (optional): `[SHOW_QR]`, `[REQUEST_PASSWORD]`, `[SHOW_BRAID_GRAPH]` —',
  '  Ronbot shows them in-thread or in a small helper; see `~/.hermes/ELECTRON_APP_GUIDE.md`.',
  '- **Intent replies** from the user: fenced ```ronbot-intent-response``` with your `id`.',
  '- **Full wire format:** `~/.ronbot/APP_GUIDE.md`.',
  '- **App routes / diagnostics:** `~/.hermes/ELECTRON_APP_GUIDE.md` (`#/diagnostics` support bundle).',
  '',
].join('\n');

export const RONBOT_APP_GUIDE_VERSION = '<!-- ronbot-app-guide v5 -->';

export const RONBOT_ELECTRON_APP_GUIDE_VERSION = '<!-- ronbot-electron-app-guide v6 -->';

export const RONBOT_ELECTRON_APP_GUIDE = [
  RONBOT_ELECTRON_APP_GUIDE_VERSION,
  '# Ronbot + Hermes on this machine',
  '',
  '## Hermes workspace',
  '',
  '- Agent files: `~/.hermes/` — `SOUL.md`, `AGENTS.md`, memories, skills, config.',
  '- UI protocol detail: `~/.ronbot/APP_GUIDE.md`.',
  '- CLI: `hermes chat` loads workspace docs unless `--ignore-rules` is set.',
  '',
  '## Saved Personalities',
  '',
  '- Presets: `~/.hermes/personalities/<name>/`. Apply via `#/settings` → Saved Personalities.',
  '- Applying a preset overwrites live files (with backup) and restarts the gateway.',
  '',
  '## App Diagnostics',
  '',
  '- `#/diagnostics` — health, logs, **Copy support bundle** for pasting into chat.',
  '- API keys / models: `#/secrets`, `#/models`.',
  '',
  '## Permission approval (desktop only)',
  '',
  '- Shell/file/network permission prompts may appear outside chat — Allow/Deny in the UI.',
  '',
  '## Stream markers (optional)',
  '',
  'Ronbot strips these from the visible bubble and renders them in the chat thread.',
  '',
  '- **`[SHOW_QR]`** — URL, `data:image/...`, text to encode, or a fenced `text` block with a',
  '  terminal QR matrix on the following lines.',
  '- **`[REQUEST_PASSWORD]<purpose>`** — inserts into the chat draft (not the keychain).',
  '  Prefer **`credential_request`** intent for secrets.',
  '- **`[SHOW_BRAID_GRAPH]`** — then a ```mermaid fenced block.',
  '',
  '## Ronbot desktop routes (HashRouter)',
  '',
  ...formatAppRoutesForAgentGuide(),
  '',
  '## Intent protocol',
  '',
  '- Shapes and responses: `~/.ronbot/APP_GUIDE.md`',
  '',
].join('\n');

export const RONBOT_APP_GUIDE = [
  RONBOT_APP_GUIDE_VERSION,
  '# Ronbot App Guide',
  '',
  'Reference for how Ronbot **renders** optional UI payloads in chat. Hermes chooses',
  'when to use tools, skills, and prose — this file does not change that.',
  '',
  '## What Ronbot renders',
  '',
  '| Payload | Ronbot behavior |',
  '|---------|-----------------|',
  '| ```ronbot-intent``` JSON | Inline card; user reply as ```ronbot-intent-response``` |',
  '| `[SHOW_QR]` + data | QR image or terminal matrix in the chat thread |',
  '| `[REQUEST_PASSWORD]` | Inserts into chat draft |',
  '| `[SHOW_BRAID_GRAPH]` + mermaid | Diagram in the chat thread |',
  '| Hermes stdout QR blocks | Detected and shown in-thread when present |',
  '',
  '## Hermes vs Ronbot',
  '',
  '- **Hermes:** skills, gateway, CLI, config, permissions, channels, cron.',
  '- **Ronbot:** intent cards, secrets UI, hash routes (`#/…`), diagnostics bundle.',
  '',
  '## Response cheat-sheet (`ronbot-intent-response`)',
  '',
  '| Intent type | On success | On cancel / fail |',
  '|-------------|------------|------------------|',
  '| `credential_request` | `ok: true`, `values: { KEY: "…" }` | `ok: false`, optional `reason` |',
  '| `choice` | `ok: true`, `values: { choice: "<option.value>" }` | same |',
  '| `file_pick` | `ok: true`, `path: "/absolute/path"` | same |',
  '| `confirm` | `ok: true` | `ok: false`, `reason: "cancelled"` |',
  '| `pairing_approve` | `ok: true` | `ok: false`, `reason: "rejected"` |',
  '| `qr_display` | `ok: true` after user taps done | `ok: false` |',
  '| `oauth_open` | `ok: true` after user confirms return | `ok: false` |',
  '| `progress` | *(no response)* | — |',
  '| `done` | *(no response)* | — |',
  '',
  '- **`progress`:** each update is a new assistant message with a new intent `id`.',
  '',
  '## Intent envelope',
  '',
  '```ronbot-intent',
  '{',
  '  "id": "intent_<unique>",',
  '  "type": "<one of the types below>",',
  '  "title": "Short header",',
  '  "description": "Optional body",',
  '  "openUrl": "https://optional-link.example",',
  '  "expiresInSec": 600',
  '}',
  '```',
  '',
  'User reply:',
  '',
  '```ronbot-intent-response',
  '{ "id": "intent_<same>", "ok": true, "values": {}, "path": "...", "reason": "..." }',
  '```',
  '',
  '## Intent types',
  '',
  '### credential_request — collect secrets/text',
  '```ronbot-intent',
  '{',
  '  "id": "intent_gws_oauth",',
  '  "type": "credential_request",',
  '  "title": "Google Workspace OAuth",',
  '  "fields": [',
  '    { "key": "GOOGLE_CLIENT_ID", "label": "Client ID" },',
  '    { "key": "GOOGLE_CLIENT_SECRET", "label": "Client secret", "secret": true }',
  '  ],',
  '  "materialize": true',
  '}',
  '```',
  '- `materialize` (default true): OS secrets store + `~/.hermes/.env` for Hermes.',
  '',
  '### confirm — yes/no',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "confirm", "title": "Delete config?", "destructive": true }',
  '```',
  '',
  '### choice — pick one',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "choice", "title": "Which model?",',
  '  "options": [{ "value": "a", "label": "A" }], "defaultValue": "a" }',
  '```',
  '- Response: `values.choice` = selected `value`.',
  '',
  '### qr_display — show a QR',
  '```ronbot-intent',
  '{ "id": "intent_qr", "type": "qr_display", "title": "Scan to link",',
  '  "qr": "data:image/png;base64,..." }',
  '```',
  '- Terminal matrix alternative:',
  '',
  '      [SHOW_QR]',
  '      ```text',
  '      <terminal QR block>',
  '      ```',
  '',
  '### oauth_open — open URL externally',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "oauth_open", "title": "Authorize", "url": "https://..." }',
  '```',
  '',
  '### file_pick — native picker',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "file_pick", "title": "Pick folder", "pickKind": "folder" }',
  '```',
  '',
  '### progress — heartbeat (no user input)',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "progress", "title": "Working…", "percent": 45 }',
  '```',
  '',
  '### done — setup complete',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "done", "title": "Connected", "capabilityId": "optional-id" }',
  '```',
  '',
  '### pairing_approve — pairing code',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "pairing_approve", "title": "Approve link",',
  '  "pairingCode": "AB12-CD34" }',
  '```',
  '',
].join('\n');
