// Hermes v0.13.0 sync — May 2026 (Ronbot)
import { formatAppRoutesForAgentGuide } from '@/lib/appRoutes';

/**
 * Static markdown the agent reads from disk (written by `hermes.ts`):
 *   - RONBOT_RULES_BLOCK   → injected into ~/.hermes/AGENTS.md
 *   - RONBOT_APP_GUIDE     → written to ~/.ronbot/APP_GUIDE.md
 *   - RONBOT_ELECTRON_APP_GUIDE → ~/.hermes/ELECTRON_APP_GUIDE.md (short index)
 *
 * Intent wire types: `src/lib/agentIntents/protocol.ts` (`AGENT_INTENT_TYPES`).
 * Bump version headers when content changes so guides refresh on connect.
 */

/** One-liner appended to seeded MEMORY.md when Ronbot manages persona files. */
export const RONBOT_MEMORY_UI_POINTER =
  '- **Ronbot UI:** Before driving the desktop app (intents, modals, routes), read `~/.ronbot/APP_GUIDE.md` and `~/.hermes/ELECTRON_APP_GUIDE.md`.';

export const RONBOT_RULES_BLOCK = [
  '## Ronbot desktop control panel',
  '',
  'You run inside the Ronbot desktop app. It has a real terminal, file tools,',
  'and a chat renderer that understands fenced ```ronbot-intent``` JSON cards.',
  '',
  '- Ronbot chat sends non-interactive one-shot prompts. Do not use the blocking',
  '  `clarify` tool here: for greetings and simple prompts, answer directly; when',
  '  a clarification is truly required, ask one concise question in normal prose',
  '  or use a `choice` intent.',
  '- You operate the app yourself. Run setup commands (`hermes whatsapp`,',
  '  `hermes auth google-workspace`, etc.) in your own shell — never tell the',
  '  user to "open a terminal" or "run this elsewhere".',
  '- For API keys, tokens, passwords, QRs, OAuth, confirms, and file pickers:',
  '  emit a fenced ```ronbot-intent``` JSON card (see `~/.ronbot/APP_GUIDE.md`).',
  '  NEVER ask for a secret in plain prose.',
  '- Stream markers (`[SHOW_QR]`, `[REQUEST_PASSWORD]`, `[SHOW_BRAID_GRAPH]`) are',
  '  secondary — see `~/.hermes/ELECTRON_APP_GUIDE.md`. Prefer intents for secrets and QR.',
  '- User replies arrive as ```ronbot-intent-response``` keyed by your `id`.',
  '- **Full protocol:** `~/.ronbot/APP_GUIDE.md` — types, responses, recipes.',
  '- **Routes, diagnostics, personalities:** `~/.hermes/ELECTRON_APP_GUIDE.md`.',
  '- **Troubleshooting:** tell the user to open `#/diagnostics` and click',
  '  **Copy support bundle**, then paste the result into chat.',
  '- Identify yourself by the name in `~/.hermes/SOUL.md`, never as "Hermes".',
  '',
].join('\n');

export const RONBOT_APP_GUIDE_VERSION = '<!-- ronbot-app-guide v3 -->';

export const RONBOT_ELECTRON_APP_GUIDE_VERSION = '<!-- ronbot-electron-app-guide v4 -->';

export const RONBOT_ELECTRON_APP_GUIDE = [
  RONBOT_ELECTRON_APP_GUIDE_VERSION,
  '# Ronbot + Hermes on this machine',
  '',
  '## Hermes workspace (what loads into context)',
  '',
  '- Default agent dir: `~/.hermes/` — `SOUL.md`, `AGENTS.md` (includes Ronbot’s',
  '  managed block), `memories/MEMORY.md`, `memories/USER.md`, skills, config.',
  '- Before your first UI-driven task, read `~/.ronbot/APP_GUIDE.md` (full intent spec).',
  '- Official CLI (Hermes v0.13.x): `hermes chat` auto-injects workspace docs unless',
  '  `--ignore-rules` is set.',
  '',
  '## Saved Personalities (Ronbot presets)',
  '',
  '- Snapshots live under `~/.hermes/personalities/<name>/` (SOUL, PERSONALITY, AGENTS,',
  '  memories). After install, **Default** is created from seeded files.',
  '- Applying a preset overwrites live `~/.hermes/` files (with backup) and restarts',
  '  the gateway. **No `ronbot-intent` for this** — use the UI or edit files.',
  '- **UI path:** `#/settings` → **Saved Personalities** (save / apply presets).',
  '- `ELECTRON_APP_GUIDE.md` is not duplicated per preset.',
  '',
  '## App Diagnostics and logs',
  '',
  '- Route: `#/diagnostics` — health snapshot, quick fixes, and **copyable logs**.',
  '- Three log areas: recent command errors, in-app activity, and Hermes',
  '  `~/.hermes/logs/agent.log` (tail).',
  '- **Copy support bundle** at the top collects health + failures + activity +',
  '  log tail for pasting into chat or a ticket. Do not ask the user to hunt logs',
  '  in a separate terminal.',
  '- For API keys and models, point users to `#/secrets` and `#/models`.',
  '',
  '## Capabilities and permission approval',
  '',
  '- If a tool is “unavailable”, the user may need to install/enable a skill via',
  '  `hermes` CLI and revisit `#/skills` or `#/channels`, or open `#/diagnostics`.',
  '- Ronbot may show an **in-app permission approval** dialog (not in chat) — the',
  '  user must click Allow/Deny in the desktop UI before the tool works.',
  '',
  '## Stream markers (secondary — prefer intents)',
  '',
  'Use markers only when a `ronbot-intent` card is awkward (e.g. BRAID diagrams).',
  'Ronbot strips them from the bubble and opens a modal.',
  '',
  '- **`[SHOW_QR]`** — same line: `data:image/...` URL, `https://` image, or text to',
  '  encode. Prefer **`qr_display`** intent for channel setup.',
  '- **`[REQUEST_PASSWORD]<purpose>`** — inserts into the **chat draft only**, not',
  '  the keychain. **Never use for API keys** — use **`credential_request`** instead.',
  '- **`[SHOW_BRAID_GRAPH]`** — marker on its own line, then a ```mermaid fenced block.',
  '',
  '  Example:',
  '',
  '      [SHOW_BRAID_GRAPH]',
  '      ```mermaid',
  '      flowchart LR',
  '        A --> B',
  '      ```',
  '',
  '## Ronbot desktop routes (HashRouter)',
  '',
  ...formatAppRoutesForAgentGuide(),
  '',
  '## Where the UI protocol is documented',
  '',
  '- **Every `ronbot-intent` field and response shape:** `~/.ronbot/APP_GUIDE.md`',
  '',
].join('\n');

export const RONBOT_APP_GUIDE = [
  RONBOT_APP_GUIDE_VERSION,
  '# Ronbot App Guide',
  '',
  'Authoritative reference for the Ronbot desktop renderer. `~/.hermes/AGENTS.md`',
  'points here — grep this file for JSON shapes, responses, and recipes.',
  '',
  '## Environment',
  '',
  '- Electron desktop app, NOT a headless server.',
  '- Run setup wizards yourself — do not ask the user to open a terminal.',
  '- `~/.hermes` = Hermes install; `~/.ronbot` = Ronbot-owned files (this guide).',
  '- Identify yourself by the name in `~/.hermes/SOUL.md`.',
  '- Chat prompts are non-interactive one-shots. Avoid the blocking `clarify`',
  '  tool; ask short follow-up questions in normal prose or with a `choice` intent.',
  '',
  '## Hermes context vs Ronbot UI',
  '',
  '- **Hermes owns:** skills, gateway, `hermes` subcommands, config, permissions YAML,',
  '  messaging bridges, cron.',
  '- **Ronbot owns:** `ronbot-intent` / `ronbot-intent-response` cards, secrets UI,',
  '  hash navigation (`#/…`).',
  '- No `ronbot-intent` to edit the Skills/Capabilities registry — use Hermes CLI.',
  '',
  '## Intents vs stream markers',
  '',
  '| Need | Use (preferred) | Avoid |',
  '|------|-----------------|-------|',
  '| API keys, tokens, passwords | `credential_request` | `[REQUEST_PASSWORD]` (draft only, not keychain) |',
  '| QR for WhatsApp / pairing | `qr_display` or `pairing_approve` | `[SHOW_QR]` unless trivial |',
  '| OAuth consent URL | `oauth_open` | plain link only |',
  '| Yes / no | `confirm` | prose yes/no in chat |',
  '| Pick folder/file | `file_pick` | — |',
  '| Long install / wizard | `progress` in **new messages** | — |',
  '| Setup finished | `done` | — |',
  '| BRAID / reasoning diagram | `[SHOW_BRAID_GRAPH]` + mermaid | — |',
  '',
  '## Response cheat-sheet (`ronbot-intent-response`)',
  '',
  '| Intent type | On success | On cancel / fail |',
  '|-------------|------------|------------------|',
  '| `credential_request` | `ok: true`, `values: { KEY: "…" }` per field | `ok: false`, optional `reason` |',
  '| `choice` | `ok: true`, `values: { choice: "<option.value>" }` | same |',
  '| `file_pick` | `ok: true`, `path: "/absolute/path"` | same |',
  '| `confirm` | `ok: true` (no `values`) | `ok: false`, `reason: "cancelled"` |',
  '| `pairing_approve` | `ok: true` | `ok: false`, `reason: "rejected"` |',
  '| `qr_display` | `ok: true` after user taps done | `ok: false` |',
  '| `oauth_open` | `ok: true` after user confirms return | `ok: false` |',
  '| `progress` | *(no response — informational only)* | — |',
  '| `done` | *(no response — informational only)* | — |',
  '',
  '- **`progress`:** emit **new assistant messages** with new intent cards; you cannot',
  '  update an earlier card by reusing the same `id`.',
  '',
  '## Capabilities, Skills, and Dashboard',
  '',
  '- Install/enable skills with `hermes` CLI; files under `~/.hermes/skills/`.',
  '- If the UI is stale after skill changes: user revisits `#/skills` or `#/channels`,',
  '  reconnects, or restarts gateway.',
  '- After channel setup, `done` with `capabilityId` may refresh probes (best-effort).',
  '- Missing tools: user may need in-app **permission approval** in Ronbot (not chat).',
  '  Suggest `#/diagnostics` or `#/skills`.',
  '',
  '## Intent envelope',
  '',
  '```ronbot-intent',
  '{',
  '  "id": "intent_<unique>",',
  '  "type": "<one of the types below>",',
  '  "title": "Short header",',
  '  "description": "Optional body",',
  '  "openUrl": "https://optional-link.example",',
  '  "expiresInSec": 600',
  '}',
  '```',
  '',
  'User reply:',
  '',
  '```ronbot-intent-response',
  '{ "id": "intent_<same>", "ok": true, "values": {}, "path": "...", "reason": "..." }',
  '```',
  '',
  '## Intent types',
  '',
  '### credential_request — collect secrets/text',
  '```ronbot-intent',
  '{',
  '  "id": "intent_gws_oauth",',
  '  "type": "credential_request",',
  '  "title": "Google Workspace OAuth",',
  '  "fields": [',
  '    { "key": "GOOGLE_CLIENT_ID", "label": "Client ID" },',
  '    { "key": "GOOGLE_CLIENT_SECRET", "label": "Client secret", "secret": true }',
  '  ],',
  '  "materialize": true',
  '}',
  '```',
  '- `materialize` (default true): OS secrets store + `~/.hermes/.env` for Hermes.',
  '',
  '### confirm — yes/no',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "confirm", "title": "Delete config?", "destructive": true }',
  '```',
  '',
  '### choice — pick one',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "choice", "title": "Which model?",',
  '  "options": [{ "value": "a", "label": "A" }], "defaultValue": "a" }',
  '```',
  '- Response: `values.choice` = selected `value`.',
  '',
  '### qr_display — show a QR',
  '```ronbot-intent',
  '{ "id": "intent_wa_qr", "type": "qr_display", "title": "Scan WhatsApp",',
  '  "qr": "data:image/png;base64,..." }',
  '```',
  '',
  '### oauth_open — open URL externally',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "oauth_open", "title": "Authorize", "url": "https://..." }',
  '```',
  '',
  '### file_pick — native picker',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "file_pick", "title": "Pick folder", "pickKind": "folder" }',
  '```',
  '',
  '### progress — heartbeat (no user input)',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "progress", "title": "Installing…", "percent": 45 }',
  '```',
  '',
  '### done — setup complete',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "done", "title": "Connected", "capabilityId": "whatsapp" }',
  '```',
  '',
  '### pairing_approve — pairing code',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "pairing_approve", "title": "Approve link",',
  '  "pairingCode": "AB12-CD34" }',
  '```',
  '',
  '## Recipes',
  '',
  '### WhatsApp setup',
  '1. Run `hermes whatsapp` yourself.',
  '2. PNG/base64 → `qr_display`; ASCII code → `pairing_approve`.',
  '3. `progress` heartbeats in follow-up messages while the wizard runs.',
  '4. `done` with `capabilityId: "whatsapp"`.',
  '',
  '### Google Workspace OAuth',
  '1. `hermes auth google-workspace`.',
  '2. `credential_request` for client ID/secret if needed.',
  '3. `oauth_open` with consent URL; `progress` during token exchange.',
  '4. `done` with `capabilityId: "google-workspace"`.',
  '',
  '### Telegram',
  '1. `credential_request` for `TELEGRAM_API_ID` + `TELEGRAM_API_HASH`.',
  '2. `hermes telegram`; phone code via second `credential_request` if needed.',
  '3. `done` with `capabilityId: "telegram"`.',
  '',
  '### Generic credential prompts',
  'CLI blocking on stdin for secrets: emit `credential_request`, never plain prose.',
  '',
  '## When NOT to use intents',
  '',
  'Ordinary explanations and summaries — prose only. Intents for UI interactions only.',
  '',
].join('\n');
