/**
 * Static markdown content the agent reads from disk:
 *   - RONBOT_RULES_BLOCK   → injected into ~/.hermes/AGENTS.md
 *   - RONBOT_APP_GUIDE     → written to ~/.ronbot/APP_GUIDE.md
 *
 * Pulled out of `hermes.ts` so the parent module stays focused on shell
 * orchestration. No runtime behavior — just strings + a version marker.
 */

/**
 * Tiny primer auto-injected into ~/.hermes/AGENTS.md. Just the essentials —
 * the agent greps ~/.ronbot/APP_GUIDE.md for the full intent JSON spec and
 * channel-setup recipes.
 */
export const RONBOT_RULES_BLOCK = [
  '## Ronbot desktop control panel',
  '',
  'You run inside the Ronbot desktop app. It has a real terminal, file tools,',
  'and a chat renderer that understands fenced ```ronbot-intent``` JSON cards.',
  '',
  '- You operate the app yourself. Run setup commands (`hermes whatsapp`,',
  '  `hermes auth google-workspace`, etc.) in your own shell — never tell the',
  '  user to "open a terminal" or "run this elsewhere".',
  '- For passwords, codes, QRs, OAuth links, confirms, file pickers, and',
  '  long-running progress: emit a fenced ```ronbot-intent``` JSON card.',
  '  NEVER ask for a secret in plain prose.',
  '- The user reply comes back as a ```ronbot-intent-response``` block keyed',
  '  by the `id` you chose.',
  '- Full intent envelope, every type with JSON examples, and end-to-end',
  '  recipes (WhatsApp QR pairing, Google Workspace OAuth, Telegram, generic',
  '  credential prompts) live in `~/.ronbot/APP_GUIDE.md` — read or grep it',
  '  whenever you are unsure what shape to emit.',
  '- Identify yourself by the name in `~/.hermes/SOUL.md`, never as "Hermes".',
  '',
].join('\n');

export const RONBOT_APP_GUIDE_VERSION = '<!-- ronbot-app-guide v1 -->';

/**
 * Full reference for the Ronbot UI protocol. Written to ~/.ronbot/APP_GUIDE.md
 * on every connect (idempotent via version header).
 */
export const RONBOT_APP_GUIDE = [
  RONBOT_APP_GUIDE_VERSION,
  '# Ronbot App Guide',
  '',
  'This file is the authoritative reference for talking to the Ronbot desktop',
  'renderer. AGENTS.md only points here — grep this file whenever you need',
  'the exact JSON shape for a UI card, or a worked recipe for a multi-step',
  'channel/auth setup.',
  '',
  '## Environment',
  '',
  '- You are running inside an Electron desktop app, NOT a headless server.',
  '- A real shell is available — run setup wizards yourself with',
  '  `subprocess`/your shell tool. Do not ask the user to open a terminal.',
  '- `~/.hermes` is your install dir; `~/.ronbot` is the app-owned dir.',
  '- Identify yourself by the name in `~/.hermes/SOUL.md`.',
  '',
  '## Intent envelope',
  '',
  'Whenever you need the user to type a secret, scan a QR, click a link,',
  'confirm something, pick a file, or watch a long task, emit a fenced JSON',
  'block. The renderer hides the raw JSON and renders an inline UI card.',
  '',
  '```ronbot-intent',
  '{',
  '  "id": "intent_<unique>",',
  '  "type": "<one of the types below>",',
  '  "title": "Short header",',
  '  "description": "Optional 1-2 sentence body",',
  '  "expiresInSec": 600',
  '}',
  '```',
  '',
  'The user reply arrives on the next turn as:',
  '',
  '```ronbot-intent-response',
  '{ "id": "intent_<same>", "ok": true, "values": { "FIELD_KEY": "..." } }',
  '```',
  '',
  '`ok: false` means the user cancelled or the card expired (`reason` may',
  'explain). Never proceed with a setup as if you got the value.',
  '',
  '## Intent types',
  '',
  '### credential_request — collect secrets/text',
  '```ronbot-intent',
  '{',
  '  "id": "intent_gws_oauth",',
  '  "type": "credential_request",',
  '  "title": "Google Workspace OAuth",',
  '  "description": "Paste the client ID and secret from the Google Cloud Console.",',
  '  "fields": [',
  '    { "key": "GOOGLE_CLIENT_ID", "label": "Client ID" },',
  '    { "key": "GOOGLE_CLIENT_SECRET", "label": "Client secret", "secret": true }',
  '  ],',
  '  "materialize": true',
  '}',
  '```',
  'Field options: `secret` (mask), `hint`, `validate` (regex string),',
  '`defaultValue`, `optional`. Values arrive in `values` keyed by `key`.',
  '',
  '### confirm — yes/no',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "confirm", "title": "Delete config?",',
  '  "destructive": true, "confirmLabel": "Delete", "cancelLabel": "Keep" }',
  '```',
  '',
  '### choice — pick one',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "choice", "title": "Which model?",',
  '  "options": [',
  '    { "value": "gpt-4o", "label": "GPT-4o", "description": "Fast & cheap" },',
  '    { "value": "claude-sonnet", "label": "Claude Sonnet" }',
  '  ], "defaultValue": "gpt-4o" }',
  '```',
  '',
  '### qr_display — show a QR for the user to scan',
  '```ronbot-intent',
  '{ "id": "intent_wa_qr", "type": "qr_display", "title": "Scan with WhatsApp",',
  '  "qr": "data:image/png;base64,iVBORw0K...",',
  '  "pairingCode": "AB12-CD34" }',
  '```',
  '',
  '### oauth_open — open a URL externally and wait',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "oauth_open", "title": "Authorize Google",',
  '  "url": "https://accounts.google.com/o/oauth2/v2/auth?..." }',
  '```',
  '',
  '### file_pick — native folder/file picker',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "file_pick", "title": "Pick project folder",',
  '  "pickKind": "folder" }',
  '```',
  '',
  '### progress — heartbeat, no input',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "progress", "title": "Installing bridge…",',
  '  "percent": 45, "status": "Downloading dependencies" }',
  '```',
  '',
  '### done — multi-step setup completed',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "done", "title": "WhatsApp connected",',
  '  "capabilityId": "whatsapp", "message": "Bridge is online." }',
  '```',
  '',
  '### pairing_approve — display a pairing code',
  '```ronbot-intent',
  '{ "id": "intent_x", "type": "pairing_approve", "title": "Approve Matrix link",',
  '  "pairingCode": "AB12-CD34", "platform": "Matrix",',
  '  "instructions": "Enter this code on your phone." }',
  '```',
  '',
  '## Recipes',
  '',
  '### WhatsApp setup',
  '1. Run `hermes whatsapp` (or the configured WhatsApp setup command) yourself.',
  '2. The wizard prints either a PNG path, a base64 QR blob, or an ASCII QR.',
  '   - If PNG path: read it, base64-encode, emit `qr_display` with',
  '     `"qr": "data:image/png;base64,<...>"`.',
  '   - If raw base64: pass through unchanged.',
  '   - If ASCII-only: emit a `pairing_approve` card with the pairing code.',
  '3. While the wizard is still running, send `progress` heartbeats so the',
  '   user knows it is alive.',
  '4. On success, emit `done` with `capabilityId: "whatsapp"`.',
  '',
  '### Google Workspace OAuth',
  '1. Run `hermes auth google-workspace`.',
  '2. If the wizard wants client credentials, emit a `credential_request`',
  '   for `GOOGLE_CLIENT_ID` + `GOOGLE_CLIENT_SECRET` (`secret: true`).',
  '3. When it prints the consent URL, emit `oauth_open` with that `url`.',
  '4. After the user clicks "I\'m back", continue the wizard. Stream',
  '   `progress` updates while tokens exchange.',
  '5. End with `done` and `capabilityId: "google_workspace"`.',
  '',
  '### Telegram',
  '1. `credential_request` for `TELEGRAM_API_ID` + `TELEGRAM_API_HASH`',
  '   (https://my.telegram.org).',
  '2. Run `hermes telegram` and surface any phone-code prompt as a second',
  '   `credential_request` with one non-secret field.',
  '3. `done` with `capabilityId: "telegram"`.',
  '',
  '### Generic credential prompts',
  'Whenever a CLI you are running blocks on stdin asking for a token, key,',
  'password, or code: stop, emit a `credential_request`, and write the value',
  'back to the process stdin (or restart the command with the env var set).',
  'Never ask in plain prose.',
  '',
  '## When NOT to use intents',
  '',
  'For ordinary explanations, status, plans, or summaries — just write prose.',
  'Intents are only for things the renderer needs to render specially.',
  '',
].join('\n');
